### ISSUE TITLE
Status check

### ISSUE THREAD

**Issue by vreuter** [pepkit/geofetch#11]
At least when running `sra_convert` via `looper` and using the `--lump` option, `looper check` doesn't correctly provide a readout of the status of each conversion in progress, instead reporting nothing. It seems like this may be due to the location and/or non-granular path for, e.g. the `_running.flag` files.

**Comment by nsheff** [comment]
I believe his is not a problem with `--lump`, but a symptom of #4. Should be solved when that gets addressed.

**Comment by vreuter** [comment]
Cool, noticed the lock files were going there too so that makes sense
