### ISSUE TITLE
Can't download SRRs larger than 50GB

### ISSUE THREAD

**Issue by drejom** [pepkit/geofetch#113]
Hi,
This is an awesome suite of packages, very excited to try it out but hit a snag off the bat with a 10X dataset of 13 samples. With `geofetch -i GSE133181`, only 6 fastqs are fetched. The remainder are skipped because they exceed the (hard-coded?) limit:

https://github.com/pepkit/geofetch/blob/cb1c4e4b5de05f84c666da720581e019658c4019/geofetch/utils.py#L84

Is it possible to override that somehow?

**Comment by nsheff** [comment]
Indeed, that is a problem. I thought it was customizable with `--filter-size` but it looks like that's only customizable for processed data, not raw data...

@Khoroshevskyi can you make this a configurable option? It should be pretty simple.

**Comment by vreuter** [comment]
@nsheff i'm on a train but had put in a quick fix for this before leaving, just hadn't pushed changes

**Comment by vreuter** [comment]
@nsheff i'm on a train but had put in a quick fix for this before leaving, just hadn't pushed changes

**Comment by drejom** [comment]
Thanks so much!! Back on track
