### ISSUE TITLE
add pipeline interface argument

### ISSUE THREAD

**Issue by nsheff** [pepkit/geofetch#12]
`geofetch` could add a new command-line argument that would allow the user to automatically add a `pipeline_interface` attribute to the project, so it doesn't have to be done afterwards manually.

**Comment by nsheff** [comment]
`-pipe` doesn't seem right, should it have 2 hypens?

Also not sure if `pipe` is the best name.

otherwise I think that's fine.

**Comment by aaron-gu** [comment]
I gave it two names, "-pipe" and "--pipeline_interfaces". What name should I change -pipe to? Should it also include two dashes before it?

**Comment by nsheff** [comment]
I see. convention is that single-hyphen commands are one letter, double-hyphen commands are words. So, do:

`-p` or `--pipeline_interfaces`

**Comment by nsheff** [comment]
@aaron-gu FYI you can close issues right from commits by including "Fix #12" in your commit message.

**Comment by aaron-gu** [comment]
Cool, good to know! I fixed this in my local branch but forgot to push it :(
