### ISSUE TITLE
Download metadata from SRA

### ISSUE THREAD

**Issue by amnahsiddiqa** [pepkit/geofetch#123]
Hi there, I really appreciate this nice package for allowing the data from GEO/SRA in automated workflow so easily through all the efforts that you have done to create PEPs.  I have been enjoying tow work with it and integrate it in my metadata analyses. But I think I might be missing something here. I have been able to use geofetch for GEO datasets but now I have started working with SRA and wanted to only download metadata from SRA. Attached image is an example of the data that I need to process. I want to create PEPs using SRA study accession. I was trying it the same way like I did successfully for GEO study accessions `geofetch -i SRS16921762 --just-metadata` but it does not work because this command only works with GSM and GSE. I just wanted to know, Am I missing something here ?
<img width="1431" alt="Screenshot 2023-09-18 at 2 41 17 PM" src="https://github.com/pepkit/geofetch/assets/28387956/0e4b0b50-fe60-4d6b-9a5f-ee706e50988e">

Many Thanks,
Amnah

**Comment by khoroshevskyi** [comment]
Hello!
I regret to inform you that geofetch currently supports only GSE input format (e.g., `-i GSE123456`). SRA represents a sample accession number in the SRA database. Geofetch is designed to search for and download data from the GEO database.

We are considering the addition of functionality that would allow downloading samples using SRA accession numbers. If this feature is added in the future, we will inform you about it.
Thank you!

**Comment by amnahsiddiqa** [comment]
Appreciate that. Thanks!!
