### ISSUE TITLE
how to get GSE information for  a SRR run id?

### ISSUE THREAD

**Issue by lizhebio** [pepkit/geofetch#136]
hello, guys.
    I need to query  GEO information for a SRR id list,  can I use this tool?

**Comment by khoroshevskyi** [comment]
Hello,

Unfortunately, with geofetch, querying GEO or downloading PEP/ files using SRR ids isn't supported.
We are considering adding this functionality to geofetch in the future.

Related issue: #123

**Comment by khoroshevskyi** [comment]
I assume this issue is solved. closing ...
