### ISSUE TITLE
change csv to tsv?

### ISSUE THREAD

**Issue by nsheff** [pepkit/geofetch#21]
because it's common that GEO metadata submitters include commas in the 'description' fields, I think we should switch our sample annotation csv output to `tsv`. this would just make it easier for very simple, delimiter software (like `cat data.csv | perl -pe 's/((?<=,)|(?<=^)),/ ,/g;' | column -t -s, | less -S`) to do something meaningful and not get messed up by within-field commas. I think within-field tabs are less frequent.

**Comment by vreuter** [comment]
:+1:

**Comment by nsheff** [comment]
Maybe an alternative would be to replace all commas in metadata fields with semicolons? then we can still use csv.

**Comment by Khoroshevskyi** [comment]
@nsheff  could you please provide example, where csv file with commas will have issues. 
I've used csv files with commas in peppy and I didn't have any problems.

**Comment by nsheff** [comment]
The example of where it will have issues is above. But, let's just decide not do this, since those use cases are rare, and I guess I'll chose to put higher value on the ubiquity of csv.
