### ISSUE TITLE
update to new pep spec

### ISSUE THREAD

**Issue by nsheff** [pepkit/geofetch#36]
When the pep spec is released, geofetch will need to write the new spec.

BTW, @stolarczyk -- here's another example use case of writing a pep object to disk.

**Comment by nsheff** [comment]
@Khoroshevskyi I believe geofetch is writing in the PEP 2.0 specfication, right? if so, this can be closed.

**Comment by Khoroshevskyi** [comment]
> @Khoroshevskyi I believe geofetch is writing in the PEP 2.0 specfication, right? if so, this can be closed.

Yes, geofetch produces PEP 2.0.0 for raw data and PEP 2.1.0 for processed data. I would change PEP 2.0.0 to 2.1.0 for raw data and then close this issue.
