### ISSUE TITLE
spaces in sample names

### ISSUE THREAD

**Issue by nsheff** [pepkit/geofetch#37]
geofetch currently allows spaces in sample names in the accession file format. these should be disallowed as they cause downstream challenges.

**Comment by nsheff** [comment]
Probably. here's an example:

```
GSE185701	GSM5621756	Huh7 siNC H3K27ac
GSE185701	GSM5621756	Huh7_siNC_H3K27ac
GSE185701	GSM5621758	Huh7_siDHX37_H3K27ac
GSE185701	GSM5621758	Huh7_siDHX37_H3K27ac
GSE185701	GSM5621760	Huh7_DHX37
GSE185701	GSM5621760	Huh7_DHX37
GSE185701	GSM5621761	Huh7_PLRG1
GSE185701	GSM5621761	Huh7_PLRG1
```

The first one has spaces. I wasn't able to test it due to #58

**Comment by Khoroshevskyi** [comment]
> What way should it be changed then? Should we replace spaces with underscore?

After discussion: spaces should be replaced by underscore.
