### ISSUE TITLE
ignore case in filter regex

### ISSUE THREAD

**Issue by stolarczyk** [pepkit/geofetch#42]
I'm writing a universal `--filter` to match processed files with genomic regions. This is what I have:

```
(narrowPeak|bed|bedGraph|bw|bigBed){1}(\.gz)?$
```

 However, I realized that there are `*.bedgraph` and `*.bedGraph` files out there, so I'd need to either include `bedgraph` to my "OR" collection or ignore case in the regex. The `re.compile` method does not seem to accept `/<regex>/i`, but `re.compile("<regex>", re.IGNORECASE)`. Therefore there's no way to do this on the command line. It would be nice to make it possible.

**Comment by Khoroshevskyi** [comment]
Was fixed in the v0.8.0
