### ISSUE TITLE
Add file size filter for processed files

### ISSUE THREAD

**Issue by Khoroshevskyi** [pepkit/geofetch#44]
Possibility of filtering processed files by size before downloading can be very useful option in geofetch.

**Comment by nsheff** [comment]
do you have access to the file size of the file so you can filter before downloading?

**Comment by Khoroshevskyi** [comment]
> do you have access to the file size of the file so you can filter before downloading?

Yes, for each ".tar" file in the same directory is additional file "filelist.txt" ,which contains the information about files in it. 
e.g. for the [Series GSE152804](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE152804) all the files and "filelist.txt" can be find here:  
- https://ftp.ncbi.nlm.nih.gov/geo/series/GSE152nnn/GSE152804/suppl/

**Comment by nsheff** [comment]
excellent. you can make it understand a parameter in gigabytes that would be useful. Or you could parse "GB" and "MB" and have them pass as "5 GB" or "500 MB"

**Comment by Khoroshevskyi** [comment]
MB and GB possibility great idea! 
However there is one other problem. There are also file that could be not in .tar archive and therefore they are not listed in the "fileslist". I see only one solution in this case: 
1) Download index.html file (information about repository)
2) Retrieve size of the files from html document

**Comment by Khoroshevskyi** [comment]
Added --filter-size argument:  #50

**Comment by nsheff** [comment]
> Added --filter-size argument: Fixed #50

Are you referring to the right issue here?

**Comment by Khoroshevskyi** [comment]
Was fixed in the v0.8.0
