### ISSUE TITLE
Integration of geofetch and pephub

### ISSUE THREAD

**Issue by Khoroshevskyi** [pepkit/geofetch#46]
pephub: https://github.com/pepkit/pephub

Ideas of integration are in this issue:

-https://github.com/pepkit/pephub/issues/21#issuecomment-1031845421

-------
Additionaly: 
- Download metadata (with created pep) with 100K excessions with bedfiles
- Think about reorganization of geofetch code, so it can be easily  integrated with pephub

**Comment by nsheff** [comment]
The reorganization is complete now, right?

**Comment by Khoroshevskyi** [comment]
Yes, the reorganization is complete. This issue is also link to the issue of the integration with pephub. So I am not sure if we want to close this issue
