### ISSUE TITLE
Fix PyPI readme formatting

### ISSUE THREAD

**Issue by nsheff** [pepkit/geofetch#48]
on pypi the readme is not formatting markdown correctly.

https://pypi.org/project/geofetch/

![image](https://user-images.githubusercontent.com/5271009/154725971-a9009981-69c0-4b92-acb4-bcfb11042c23.png)

**Comment by Khoroshevskyi** [comment]
I am not sure where was, or still is the problem, but I have changed src, and It should fix this issue.

**Comment by Khoroshevskyi** [comment]
There is still the issue on the pypi, previous fix didn't help

**Comment by Khoroshevskyi** [comment]
Setup script was changed, I assume it will fix this issue.

**Comment by Khoroshevskyi** [comment]
Thre is still problem with Pypi readme. This time there is no geofetch Logo.

**Comment by nsheff** [comment]
I think that will fix it by just putting in a web url. 

I'm not sure if you can do it with a local path like we were before.
