### ISSUE TITLE
Decouple Geofetcher and argparser

### ISSUE THREAD

**Issue by Khoroshevskyi** [pepkit/geofetch#56]
The `Geofetcher` class is dependent on argparse, that provides limitations and issuses in future development. 

Decoupling of `Geofetcher` and Argparser will solve this problem.

**Comment by nsheff** [comment]
We need to use `Geofetcher` in scenarios where we won't have a CLI.

**Comment by nsheff** [comment]
I don't believe this change was reflected in the changelog, was it?

**Comment by Khoroshevskyi** [comment]
> I don't believe this change was reflected in the changelog, was it?

In changelog, I have added arguments and features that were added to geofetch. Decoupling of geofetcher and argparser wasn't added to changelog.
