### ISSUE TITLE
make columns case insensitive

### ISSUE THREAD

**Issue by Khoroshevskyi** [pepkit/geofetch#68]
Now columns in csv are case sensitive.
e.g.: 
 - Assembly == assembly == ASSEMBLY
 - Genome_build == genome_build == Genome build
 - 
Also we want to replace spaces to underscoreю

**Comment by Khoroshevskyi** [comment]
Solved!

**Comment by nleroy917** [comment]
Didn't realize this was already an issue, and I made a dup: #71 Sorry!
