### ISSUE TITLE
Sanitize sample names

### ISSUE THREAD

**Issue by nleroy917** [pepkit/geofetch#71]
Sample names coming from GEO can be messy. This breaks some functionality within other PEP tools. Sample names should not have any odd characters like slashes (`/`) or spaces.

It would be nice to have geofetch sanitize (or have an option to sanitize) sample names.

**Example:**
`ATAC-seq from Luminal1/BMP k.o CAF-FOXA1 o.e tumor` becomes `ATAC-seq_from_Luminal1-BMP_k_o_CAF-FOXA1_o_e tumor`

Maybe the flag name could be `--sanitize-sample-names`

See https://github.com/pepkit/pephub/issues/40 for further discussion

**Comment by Khoroshevskyi** [comment]
I think this functionality has to be default, without any flag

**Comment by Khoroshevskyi** [comment]
I have added sanitize sample names functionality to geofetch. Can you please try to use it, and check if everything works correctly?
