### ISSUE TITLE
Add progress bar

### ISSUE THREAD

**Issue by Khoroshevskyi** [pepkit/geofetch#73]
It would be nice to add progress bar to geofetch. It will be super usefull when downloading hunderds of data.
Good solution is [progressbar](https://github.com/WoLpH/python-progressbar) which allows to keep logging while having the progressbar printed

**Comment by nsheff** [comment]
if you do this, you should look into how refgenie does it. I think we are using [tqdm](https://github.com/tqdm/tqdm)

**Comment by nleroy917** [comment]
+1 for `tqdm`
