### ISSUE TITLE
Fail to download GSExxxxxx_SRA.csv

### ISSUE THREAD

**Issue by shkao** [pepkit/geofetch#74]
Hi,

Thanks for developing `geofetch`!
Not sure if it also happens to anyone else,
that recently I found `geofetch` can't download a critical file (GSExxxxxx_SRA.csv),
which the program used to be able to get it, for example, `geofetch --input GSE100687 --just-metadata`:

```
$ ls -l GSE100687/
total 28
-rw-rw-r--. 1 alkao alkao  3589 Jul  5 18:36 GSE100687_annotation.csv
-rw-rw-r--. 1 alkao alkao  1679 Jul  5 18:36 GSE100687_config.yaml
-rw-rw-r--. 1 alkao alkao  2486 Jul  5 18:36 GSE100687_GSE.soft
-rw-rw-r--. 1 alkao alkao 14802 Jul  5 18:36 GSE100687_GSM.soft
-rw-rw-r--. 1 alkao alkao     0 Jul  5 18:36 GSE100687_SRA.csv
-rw-rw-r--. 1 alkao alkao     0 Jul  5 18:36 GSE100687_SRA_filt.csv

$ geofetch -V
geofetch 0.9.0
```

I suspect that it's related to the following log information (here's to the full log: [geofetch_log.txt](https://github.com/pepkit/geofetch/files/9045683/geofetch_log.txt)):

```
--2022-07-05 18:36:22--  https://www.ncbi.nlm.nih.gov/sviewer/?db=sra&1%3Fdb=sra&rettype=runinfo&save=efetch&term=SRP110816
Reusing existing connection to www.ncbi.nlm.nih.gov:443.
HTTP request sent, awaiting response... 400 Bad Request. Both list of IDs and query_key are empty
2022-07-05 18:36:23 ERROR 400: Bad Request. Both list of IDs and query_key are empty.
```

I'll see what I can do. And would be great to have a look together.

**Comment by Khoroshevskyi** [comment]
Thanks for reporting the issue! 
The problem is with:  [NCBI Trace database to be retired in June 2022. Data available in SRA.](https://ncbiinsights.ncbi.nlm.nih.gov/2021/12/17/trace-archive-retirement/)
We are working to resolve the problem as quickly as we can.

**Comment by shkao** [comment]
This is great, thank you, @Khoroshevskyi !
