### ISSUE TITLE
Issues in getting sra file with post request

### ISSUE THREAD

**Issue by Khoroshevskyi** [pepkit/geofetch#82]
in previous issue  #77 we were changing get request to post as we could run multiple samples in one request.
Now I'm facing the following problem: if there is more samples then N number, then we are getting next error: 

![image](https://user-images.githubusercontent.com/41573628/185653488-c3e5fc30-2ea7-4daa-9c3f-00888dffa4b9.png)

**Comment by nsheff** [comment]
this should only happen for a GET request, right? not for a POST

**Comment by Khoroshevskyi** [comment]
This error happend while using POST. Additionally I found another bug. 
Everything is fixed now. I will make new pull request soon

**Comment by nsheff** [comment]
Strange. POST shouldn't affect the URL length.

**Comment by Khoroshevskyi** [comment]
any request has some length limitations, so there was incorrect input with 500+ accessions, and it caused an error
