### ISSUE TITLE
colons in values

### ISSUE THREAD

**Issue by nsheff** [pepkit/geofetch#92]
geofetch should quote any constant columns its sticking in the config, since embedded colons are causing problems.

**Comment by nsheff** [comment]
GSE181846

**Comment by Khoroshevskyi** [comment]
In geofetch0.11.0 this error is solved by deleting all special characters. Not sure if it's the best solution, but I decided to do this, as quoted text was causing errors, because some of the text in GEO and NCBI had double or single quotes.

**Comment by Khoroshevskyi** [comment]
`geofetch -i GSE181846 --metadata-folder `pwd` --just-metadata --const-limit-project 1 --const-limit-discard 10000 --attr-limit-truncate 10000`
You can run this command using geofetch from this branch: `https://github.com/pepkit/geofetch/tree/refactoring`

**Comment by nsheff** [comment]
I would suggest:

1. quote the fields
2. escape any internal quotes.

Would that work? I think it's better than stripping characters.
